spring:
  datasource:
    username: root
    password: 1q2w3e4r!@#$
    mapper-locations: classpath:/Mapper/**/*.xml
    jdbc-url: jdbc:log4jdbc:mysql://13.124.168.134:3307/shoppingMall?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: off
      audit: off
      resultset: off
      connection: off

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml

server:
  port: 8080
  servlet: 
    session: 
      cookie: 
        same-site: none
        secure: true